version: '2.1'

services:
  ngeo:
    image: ngeo
    build: .
    ports:
      - 3000:3000
    volumes: 
      - ./:/usr/src/app/
      - /usr/src/app/.build
      - /usr/src/app/node_modules
    network_mode: bridge
